# Generated by Django 4.2.20 on 2026-05-29 04:01

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.utils.uuidv7
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/collections')),
                ('score', models.IntegerField(default=0, null=True)),
                ('item_count', models.IntegerField(default=0)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('released', models.BooleanField(default=False)),
                ('metadatas', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_official', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('invalid_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('pending_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('parents', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_collection', to='core.collection')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_collection', to='core.collection')),
            ],
            options={
                'db_table': 'collection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(default='unsplash', max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.UUIDField(default=utils.utils.uuidv7.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/upload/images'), upload_to='v1/')),
                ('url', models.URLField(db_index=True, max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('provider', models.CharField(default='unsplash', max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sub_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('value', models.CharField(max_length=255)),
                ('reading', models.TextField(blank=True, null=True)),
                ('roman', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list, null=True)),
                ('antonyms', models.JSONField(blank=True, default=list, null=True)),
                ('relateds', models.JSONField(blank=True, default=list, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('rubys', models.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(default=100, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_fixed', models.BooleanField(default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'word',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('sub_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=100, null=True)),
                ('ipas', models.JSONField(blank=True, default=list, null=True)),
                ('audios', models.JSONField(blank=True, default=list, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('interesting_info', models.TextField(blank=True, null=True)),
                ('tip', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('topics', models.JSONField(blank=True, default=list, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'word_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('sub_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, max_length=50, null=True)),
                ('type', models.JSONField(blank=True, default=list, null=True)),
                ('roman', models.TextField(blank=True, null=True)),
                ('ruby', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_forms', to='core.word')),
            ],
            options={
                'db_table': 'word form',
                'ordering': ['value', 'type'],
            },
        ),
        migrations.AddField(
            model_name='word',
            name='word_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.wordinfo'),
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sub_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('learned_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('sync', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to='core.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('question_type', models.CharField(choices=[('meaning', 'Meaning'), ('usage', 'Usage')], default='meaning', max_length=20)),
                ('answer_type', models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('fill-in', 'Fill in')], default='multiple-choice', max_length=20)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='ai.aisense')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ai.aisense')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], default='ltr', max_length=3, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('is_supported', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'language',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImageLibraryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagecontext')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagelibrary')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='images',
            field=models.ManyToManyField(related_name='contexts', through='core.ImageLibraryContext', to='core.imagelibrary'),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.FloatField(default=0.0, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('is_base', models.BooleanField(default=True, null=True)),
                ('is_deleted', models.BooleanField(null=True)),
                ('version', models.IntegerField(default=None, null=True)),
                ('released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=None, null=True, size=None)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_items', to='ai.aisense')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sense_items', to='ai.aisense')),
            ],
            options={
                'db_table': 'collection_items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='senses',
            field=models.ManyToManyField(blank=True, through='core.CollectionItem', to='ai.aisense'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(blank=True, to='utils.tag'),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wordinfo',
            index=models.Index(fields=['-created_at'], name='word_info_created_0835b0_idx'),
        ),
        migrations.AddIndex(
            model_name='wordinfo',
            index=models.Index(fields=['pos'], name='word_info_pos_013fea_idx'),
        ),
        migrations.AddIndex(
            model_name='wordinfo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='wordinfo_tags_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='wordform',
            index=models.Index(fields=['value'], name='word form_value_ace5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['value'], name='word_value_d238dd_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language_code', 'value', '-created_at'], name='word_languag_95e6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['-created_at'], name='word_created_361065_idx'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['is_active', 'is_deleted', '-created_at'], name='downloaded_collection_idx'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['user', '-created_at'], name='core_userco_user_id_2f7a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['sense', 'level', 'is_active', 'is_deleted'], name='idx_quiz_lookup'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_by', 'is_deleted'], name='note_created_98d0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['sense', 'created_by'], name='note_sense_i_cfc28e_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sense', 'created_by'), name='unique_user_sense_note'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='language_code_5bf85d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagelibrarycontext',
            index=models.Index(fields=['context', 'order'], name='idx_ctx_order'),
        ),
        migrations.AlterUniqueTogether(
            name='imagelibrarycontext',
            unique_together={('image', 'context')},
        ),
        migrations.AddConstraint(
            model_name='imagelibrary',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_id__isnull', False)), fields=('provider', 'provider_id'), name='unique_provider_image_id'),
        ),
        migrations.AlterUniqueTogether(
            name='imagecontext',
            unique_together={('description', 'provider')},
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'order'], name='collection__collect_9c3f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['sense', 'collection'], name='collection__sense_i_e811ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'sense')},
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['language_code', 'is_active', 'is_deleted', '-score'], name='idx_coll_lang_score'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['language_code', 'is_active', 'is_deleted', '-created_at'], name='idx_coll_lang_created'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='collection_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
