# Generated by Django 4.2.20 on 2026-02-04 07:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.utils.uuidv7


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(default='unsplash', max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.UUIDField(default=utils.utils.uuidv7.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\Code\\flashcardApi\\upload\\images'), upload_to='v1/')),
                ('url', models.URLField(max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(default='unsplash', max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider_id', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ImageLibraryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagecontext')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagelibrary')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'unique_together': {('image', 'context')},
            },
        ),
        migrations.AddField(
            model_name='imagecontext',
            name='images',
            field=models.ManyToManyField(related_name='contexts', through='core.ImageLibraryContext', to='core.imagelibrary'),
        ),
        migrations.AlterUniqueTogether(
            name='imagecontext',
            unique_together={('description', 'provider')},
        ),
    ]
