# Generated by Django 4.2.20 on 2026-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='original_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
