# Generated by Django 4.2.20 on 2026-05-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='sub_id',
        ),
    ]
