# Generated by Django 4.2.20 on 2026-05-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collectionitem_original_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
