# Generated by Django 4.2.20 on 2026-03-25 14:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagecontext_imagelibrary_imagelibrarycontext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelibrary',
            name='file',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/upload/images'), upload_to='v1/'),
        ),
    ]
