# Generated by Django 4.2.20 on 2026-05-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aisense_global_forget_count_and_more'),
        ('core', '0003_usercollection_description_usercollection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='original_id',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_items', to='ai.aisense'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sense_items', to='ai.aisense'),
        ),
    ]
