# Generated by Django 4.2.20 on 2026-05-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_collectionitem_original_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
