# Generated by Django 4.2.20 on 2026-05-13 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collectionitem_status_collectionitem_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='invalid_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collection',
            name='peding_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
