# Generated by Django 4.2.20 on 2026-05-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_collection_invalid_words_collection_peding_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='peding_words',
            new_name='pending_words',
        ),
    ]
