# Generated by Django 4.2.20 on 2026-05-16 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_peding_words_collection_pending_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='added_sense',
        ),
        migrations.RemoveField(
            model_name='usercollection',
            name='removed_sense',
        ),
        migrations.AddField(
            model_name='usercollection',
            name='added_item_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='deleted_item_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
    ]
