# Generated by Django 4.2.20 on 2026-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usercollection_added_sense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
