# Generated by Django 4.2.20 on 2026-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usercollection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='learned_count',
            field=models.IntegerField(default=0),
        ),
    ]
