# Generated by Django 4.2.20 on 2026-05-26 04:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_collection_item_count_usercollection_learned_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collection'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['original'], name='collection_origina_605503_idx'),
        ),
    ]
