# Generated by Django 4.2.20 on 2026-05-29 04:01

from django.db import migrations, models
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.JSONField()),
            ],
            options={
                'db_table': 'dashboard_cache',
            },
        ),
        migrations.CreateModel(
            name='InterestingWord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('word_sub_id', models.CharField(max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('last_view_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interested_words',
                'ordering': ['-view_count'],
            },
        ),
        migrations.CreateModel(
            name='MostForgetWord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('word_sub_id', models.CharField(max_length=50)),
                ('forgot_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'most_forgot_words',
            },
        ),
        migrations.CreateModel(
            name='MostLikeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('collection_sub_id', models.CharField(max_length=50)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'most_liked_collections',
            },
        ),
        migrations.CreateModel(
            name='MostLikeWord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('word_sub_id', models.CharField(max_length=50)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'most_liked_words',
            },
        ),
        migrations.CreateModel(
            name='RecommendCollection',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('collection_sub_id', models.CharField(max_length=50)),
                ('strategy', models.CharField(choices=[('system', 'System'), ('personalized', 'Personalized')], max_length=32)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_cache',
            },
        ),
    ]
