# Generated by Django 4.2.20 on 2026-05-29 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
        ),
        migrations.AddField(
            model_name='recommendcollection',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AddField(
            model_name='mostlikeword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AddField(
            model_name='mostlikeword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word'),
        ),
        migrations.AddField(
            model_name='mostlikecollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
        ),
        migrations.AddField(
            model_name='mostlikecollection',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AddField(
            model_name='mostforgetword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AddField(
            model_name='mostforgetword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word'),
        ),
        migrations.AddField(
            model_name='interestingword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AddField(
            model_name='interestingword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interestingword',
            index=models.Index(fields=['language', 'view_count'], name='idx_trend_lang_views'),
        ),
    ]
