# Generated by Django 4.2.20 on 2026-05-29 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('bookmark', 'Bookmark')], default='like', max_length=20)),
                ('is_liked', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=0)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interaction',
            },
        ),
        migrations.RenameField(
            model_name='learnsession',
            old_name='word_count',
            new_name='sense_count',
        ),
        migrations.RenameField(
            model_name='learnsession',
            old_name='words',
            new_name='senses',
        ),
        migrations.AlterField(
            model_name='learnsession',
            name='type',
            field=models.CharField(choices=[('learn', 'Learn'), ('quicklearn', 'Quick Learn'), ('recall', 'Recall'), ('review', 'Review')], default='learn', max_length=20),
        ),
        migrations.DeleteModel(
            name='LikeCollection',
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type', 'content_type', 'object_id'], name='user_intera_user_id_2a1c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['content_type', 'object_id'], name='user_intera_content_95ce47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'interaction_type', 'content_type', 'object_id')},
        ),
    ]
