# Generated by Django 4.2.20 on 2026-05-30 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interact', '0003_remove_forgetword_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='user_intera_user_id_2a1c9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinteraction',
            name='user_intera_content_95ce47_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='target_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('word', 'Word'), ('sense', 'Sense'), ('quiz', 'Quiz')], default='like', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'interaction_type', 'target_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type', 'target_type', 'target_id'], name='user_intera_user_id_37bc00_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type', 'interaction_type', 'status'], name='user_intera_user_id_14cc48_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['target_type', 'target_id'], name='user_intera_target__71f912_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['interaction_type', 'status'], name='user_intera_interac_6a9466_idx'),
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='version',
        ),
    ]
