from Feedback import FeedbackSerializer
from ForgetWord import ForgetWordSerializer
from LearnSession import LearnSessionSerializer
from LearnWord import LearnWordSerializer
from LikeCollection import LikeCollectionSerializer
from LikeWord import LikeWordSerializer
from Report import ReportSerializer
from UpdateLog import UpdateLogSerializer
from UpdateRequest import UpdateRequestSerializer
from ViewCollection import ViewCollectionSerializer
from ViewWord import ViewWordSerializer
from WordStatus import WordStatusSerializer