from core.models.Collection import Collection
from core.models.CommonPhrase import CommonPhrase
from core.models.Defination import Defination
from core.models.UserCollection import UserCollection
from core.models.Example import Example
from core.models.ExampleTranslate import ExampleTranslate
from core.models.Language import Language
from core.models.Quiz import Quiz
from core.models.Translate import Translate
from core.models.Word import Word
from core.models.WordForm import WordForm
from core.models.WordInfo import WordInfo
from core.models.Note import Note