# Generated by Django 4.2.20 on 2026-05-30 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProvider',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('github', 'GitHub'), ('x', 'X (Twitter)')], max_length=50)),
                ('provider_user_id', models.CharField(db_index=True, max_length=255)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_provider',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('refresh_token_jti', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_session',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='banlist',
            name='banned_by',
        ),
        migrations.RemoveField(
            model_name='banlist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='banlist',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='banlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='login',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='login',
            name='device',
        ),
        migrations.RemoveField(
            model_name='login',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='loginprovider',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='loginprovider',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loginprovider',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='loginprovider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='app_language',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='language',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='learning_language',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='token',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='token',
            name='device',
        ),
        migrations.RemoveField(
            model_name='token',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='purchaserecord',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_user_id_2c597b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='restrictlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider_user_id',
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='push_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_xp',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='store_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('progress', 'Progress'), ('remind', 'Remind')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('guest', 'Guest'), ('normal_user', 'Normal User'), ('VIP', 'VIP User'), ('admin', 'Admin/Staff')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_zone',
            field=models.CharField(blank=True, default='Asia/Ho_Chi_Minh', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zone_num',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='currency',
            field=models.CharField(default='VND', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='platform',
            field=models.CharField(choices=[('google', 'Google Play'), ('apple', 'App Store'), ('stripe', 'Stripe (Web)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='purchase_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='purchased_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='receipt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restrictlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', '-last_seen_at'], name='device_user_id_4d4cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_366c29_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['zone_num', 'fav_time'], name='profile_zone_nu_5eb648_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['status', 'expired_at'], name='purchase_re_status_71b90d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserecord',
            index=models.Index(fields=['user', '-purchased_at'], name='purchase_re_user_id_c72c67_idx'),
        ),
        migrations.AddIndex(
            model_name='restrictlist',
            index=models.Index(fields=['user', 'is_blocked', 'is_muted'], name='restricted__user_id_0ee301_idx'),
        ),
        migrations.AddConstraint(
            model_name='restrictlist',
            constraint=models.UniqueConstraint(fields=('user', 'target'), name='unique_user_target_restrict'),
        ),
        migrations.AlterModelTable(
            name='purchaserecord',
            table='purchase_record',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BanList',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='LoginProvider',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user.device'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersetting',
            index=models.Index(fields=['user', 'key'], name='user_settin_user_id_25d0cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('user', 'key')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_4f7411_idx'),
        ),
        migrations.AddIndex(
            model_name='accountprovider',
            index=models.Index(fields=['provider', 'provider_user_id'], name='account_pro_provide_500173_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountprovider',
            unique_together={('user', 'provider')},
        ),
    ]
