# Generated by Django 4.2.20 on 2026-05-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_accountprovider_usersession_usersetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=20)),
                ('native_language', models.CharField(blank=True, max_length=50)),
                ('learning_languages', models.JSONField(blank=True, default=list)),
                ('fav_time', models.TimeField(blank=True, null=True)),
                ('level', models.IntegerField(db_index=True, default=1)),
                ('total_xp', models.PositiveIntegerField(db_index=True, default=0)),
                ('current_streak', models.PositiveIntegerField(db_index=True, default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('guest', 'Guest'), ('normal_user', 'Normal User'), ('VIP', 'VIP User'), ('admin', 'Admin/Staff')], default='guest', max_length=20)),
                ('tier_expired_at', models.DateTimeField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, default='Asia/Ho_Chi_Minh', max_length=100)),
                ('zone_num', models.IntegerField(blank=True, default=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ban_reason', models.TextField(blank=True, null=True)),
                ('ban_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['zone_num', 'fav_time'], name='user_profil_zone_nu_7b83dc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['country_code'], name='user_profil_country_cdde60_idx'),
        ),
    ]
