# Generated by Django 4.2.20 on 2026-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(max_length=255)),
                ('target_word', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=10)),
                ('translate_language_code', models.CharField(max_length=10)),
                ('translate_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_word', '-translate_score'], name='tracking_wo_source__ba0839_idx')],
                'unique_together': {('source_word', 'target_word')},
            },
        ),
    ]
