# Generated by Django 4.2.20 on 2026-05-30 01:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifierlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modifierlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='modifierlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='monthlearnlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlearnlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='monthlearnlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='monthlearnlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weeklearnlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklearnlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='weeklearnlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='weeklearnlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='yearlearnlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='yearlearnlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='yearlearnlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='yearlearnlog',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='adminlog',
            name='admin_log_admin_i_8d6bb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminlog',
            name='admin_log_action_a2526e_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminlog',
            name='admin_log_created_f30aa4_idx',
        ),
        migrations.RemoveIndex(
            model_name='wordtranslation',
            name='tracking_wo_source__ba0839_idx',
        ),
        migrations.RemoveField(
            model_name='learnlog',
            name='session_id',
        ),
        migrations.AddField(
            model_name='learnlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='learnlog',
            name='learn_time',
            field=models.PositiveIntegerField(default=0, help_text='Thời gian học (phút hoặc giây)'),
        ),
        migrations.AddField(
            model_name='learnlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learnlog',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learnlog',
            name='words_learned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='learnlog',
            name='words_relearned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('source_word', 'target_word', 'language_code', 'translate_language_code')},
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin', '-created_at'], name='admin_log_admin_i_5dda13_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action', '-created_at'], name='admin_log_action_fa6449_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['target_type', 'target_id'], name='admin_log_target__576315_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['language_code', 'source_word', '-translate_score'], name='tracking_wo_languag_eebd74_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['translate_language_code', 'target_word', '-translate_score'], name='tracking_wo_transla_cb74fb_idx'),
        ),
        migrations.DeleteModel(
            name='ModifierLog',
        ),
        migrations.DeleteModel(
            name='MonthLearnLog',
        ),
        migrations.DeleteModel(
            name='QueryLog',
        ),
        migrations.DeleteModel(
            name='WeekLearnLog',
        ),
        migrations.DeleteModel(
            name='YearLearnLog',
        ),
    ]
