# Generated by Django 4.2.20 on 2026-02-02 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_word',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='AISenseMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('relateds', models.JSONField(blank=True, default=list)),
                ('forms', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('voted', models.IntegerField(default=0)),
                ('devoted', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('pos', models.CharField(blank=True, max_length=50, null=True)),
                ('ipas', models.JSONField(default=list)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_offensive', models.BooleanField(default=False)),
                ('register', models.CharField(default='informal', max_length=50)),
                ('image_desc', models.TextField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, max_length=500, null=True)),
                ('image_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sense_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISenseContent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.URLField(blank=True, max_length=500, null=True)),
                ('reading', models.TextField(blank=True, null=True)),
                ('roman', models.TextField(blank=True, null=True)),
                ('ruby', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_ai_created', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_sense_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISense',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('word_value', models.TextField(blank=True, null=True)),
                ('origins', models.JSONField(default=list)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contents', models.JSONField(default=dict)),
                ('news', models.JSONField(default=list)),
                ('is_frozen', models.BooleanField(default=True, null=True)),
                ('versions', models.IntegerField(default=1)),
                ('is_official', models.BooleanField(default=True)),
                ('is_ai_created', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senses', to='ai.aisensemetadata')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_sense', to='ai.aisense')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sense', to='ai.aisense')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='ai.aiword')),
            ],
            options={
                'db_table': 'ai_sense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslateLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translate_logs', to='ai.aiword')),
            ],
            options={
                'db_table': 'translate_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['word'], name='translate_l_word_id_d1ffd9_idx'), models.Index(fields=['language_code'], name='translate_l_languag_48d448_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='translatelog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PROCESSING')), fields=('word', 'language_code'), name='unique_translate_query'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['language_code'], name='ai_word_languag_207631_idx'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['created_at'], name='ai_word_created_a27d84_idx'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['value'], name='ai_word_value_dc6313_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiword',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'PROCESSING')), fields=('value', 'language_code'), name='unique_word'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['likes'], name='sense_metad_likes_66ff7e_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['views'], name='sense_metad_views_5be414_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['created_at'], name='sense_metad_created_b63d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensecontent',
            index=models.Index(fields=['language_code'], name='ai_sense_co_languag_7efd38_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensecontent',
            index=models.Index(fields=['type'], name='ai_sense_co_type_4c8ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['word'], name='ai_sense_word_id_8a6e04_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['language_code'], name='ai_sense_languag_9d1c57_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['metadata'], name='ai_sense_metadat_9e4018_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['original'], name='ai_sense_origina_49968b_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['previous'], name='ai_sense_previou_0e3f05_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_frozen'], name='ai_sense_is_froz_8d5e22_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['created_at'], name='ai_sense_created_9f86ee_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_active'], name='ai_sense_is_acti_82f308_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_deleted'], name='ai_sense_is_dele_efeea3_idx'),
        ),
    ]
