# Generated by Django 4.2.20 on 2026-03-30 02:53
# 1. Thêm dòng import này ở trên cùng
from django.contrib.postgres.operations import TrigramExtension
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='AIWord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_word',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='TranslateLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translate_logs', to='ai.aiword')),
            ],
            options={
                'db_table': 'translate_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISenseMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('relateds', models.JSONField(blank=True, default=list)),
                ('forms', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('voted', models.IntegerField(default=0)),
                ('devoted', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('pos', models.CharField(blank=True, max_length=50, null=True)),
                ('ipas', models.JSONField(default=list)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_offensive', models.BooleanField(default=False)),
                ('register', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('image_desc', models.TextField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, max_length=500, null=True)),
                ('image_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sense_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISenseContent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.URLField(blank=True, max_length=500, null=True)),
                ('reading', models.TextField(blank=True, null=True)),
                ('roman', models.TextField(blank=True, null=True)),
                ('ruby', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_ai_created', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_sense_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISense',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('word_value', models.TextField(blank=True, null=True)),
                ('origins', models.JSONField(default=list)),
                ('preview', models.JSONField(default=dict)),
                ('image_preview', models.URLField(blank=True, max_length=500, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contents', models.JSONField(default=dict)),
                ('news', models.JSONField(default=list)),
                ('is_offensive', models.BooleanField(default=False, null=True)),
                ('is_frozen', models.BooleanField(default=True, null=True)),
                ('versions', models.IntegerField(default=1)),
                ('is_official', models.BooleanField(default=True)),
                ('is_ai_created', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_sense',
                'ordering': ['-created_at'],
            },
        ),
    ]
