# Generated by Django 4.2.20 on 2026-02-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagecontext_imagelibrary_imagelibrarycontext_and_more'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisense',
            name='image_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imagecontext'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='image_preview',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aisense',
            name='preview',
            field=models.JSONField(default=dict),
        ),
    ]
