# Generated by Django 4.2.20 on 2026-05-29 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisense',
            name='image_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imagecontext'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senses', to='ai.aisensemetadata'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_sense', to='ai.aisense'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sense', to='ai.aisense'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisense',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='ai.aiword'),
        ),
        migrations.AddIndex(
            model_name='translatelog',
            index=models.Index(fields=['word'], name='translate_l_word_id_d1ffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='translatelog',
            index=models.Index(fields=['language_code'], name='translate_l_languag_48d448_idx'),
        ),
        migrations.AddConstraint(
            model_name='translatelog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PROCESSING')), fields=('word', 'language_code'), name='unique_translate_query'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['language_code', 'value'], name='idx_lang_value'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['status', 'created_at'], name='idx_status_created'),
        ),
        migrations.AddConstraint(
            model_name='aiword',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('value', 'language_code'), name='unique_active_word_lang'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['image_link'], name='idx_meta_image_link'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['created_at'], name='sense_metad_created_b63d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensecontent',
            index=models.Index(fields=['language_code'], name='ai_sense_co_languag_7efd38_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensecontent',
            index=models.Index(fields=['type'], name='ai_sense_co_type_4c8ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['word', 'is_active', 'is_deleted', 'is_official'], name='idx_sense_core_lookup'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['language_code', 'pos', 'level'], name='idx_sense_filter'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['created_at'], name='ai_sense_created_9f86ee_idx'),
        ),
    ]
