# Generated by Django 4.2.20 on 2026-03-30 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisense',
            name='image_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.imagecontext'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senses', to='ai.aisensemetadata'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_sense', to='ai.aisense'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sense', to='ai.aisense'),
        ),
        migrations.AddField(
            model_name='aisense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisense',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='ai.aiword'),
        ),
        migrations.AddIndex(
            model_name='translatelog',
            index=models.Index(fields=['word'], name='translate_l_word_id_d1ffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='translatelog',
            index=models.Index(fields=['language_code'], name='translate_l_languag_48d448_idx'),
        ),
        migrations.AddConstraint(
            model_name='translatelog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PROCESSING')), fields=('word', 'language_code'), name='unique_translate_query'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['language_code'], name='ai_word_languag_207631_idx'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['created_at'], name='ai_word_created_a27d84_idx'),
        ),
        migrations.AddIndex(
            model_name='aiword',
            index=models.Index(fields=['value'], name='ai_word_value_dc6313_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiword',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'PROCESSING')), fields=('value', 'language_code'), name='unique_word'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['likes'], name='sense_metad_likes_66ff7e_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['views'], name='sense_metad_views_5be414_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['created_at'], name='sense_metad_created_b63d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['is_offensive'], name='sense_metad_is_offe_10ae69_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensecontent',
            index=models.Index(fields=['language_code'], name='ai_sense_co_languag_7efd38_idx'),
        ),
        migrations.AddIndex(
            model_name='aisensecontent',
            index=models.Index(fields=['type'], name='ai_sense_co_type_4c8ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['word'], name='ai_sense_word_id_8a6e04_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['language_code'], name='ai_sense_languag_9d1c57_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['metadata'], name='ai_sense_metadat_9e4018_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['original'], name='ai_sense_origina_49968b_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['previous'], name='ai_sense_previou_0e3f05_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_frozen'], name='ai_sense_is_froz_8d5e22_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['created_at'], name='ai_sense_created_9f86ee_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_active'], name='ai_sense_is_acti_82f308_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_deleted'], name='ai_sense_is_dele_efeea3_idx'),
        ),
    ]
