# Generated by Django 4.2.20 on 2026-03-25 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aisense_image_context_aisense_image_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisense',
            name='is_offensive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aisensemetadata',
            name='register',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddIndex(
            model_name='aisensemetadata',
            index=models.Index(fields=['is_offensive'], name='sense_metad_is_offe_10ae69_idx'),
        ),
    ]
