# Generated by Django 4.2.20 on 2026-04-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='image_desc',
        ),
        migrations.AddField(
            model_name='aisensemetadata',
            name='image_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
