# Generated by Django 4.2.20 on 2026-04-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_remove_aisensemetadata_image_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='is_valid',
        ),
    ]
