# Generated by Django 4.2.20 on 2026-05-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_aisensemetadata_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisense',
            name='delta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='aisense',
            name='contents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
