# Generated by Django 4.2.20 on 2026-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aisense_delta_alter_aisense_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisense',
            name='global_forget_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='global_remember_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='main_count',
            field=models.IntegerField(default=0),
        ),
    ]
