# Generated by Django 4.2.20 on 2026-05-12 02:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aisense_global_forget_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aisense',
            name='ai_sense_previou_0e3f05_idx',
        ),
        migrations.RemoveIndex(
            model_name='aisensemetadata',
            name='sense_metad_likes_66ff7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='aisensemetadata',
            name='sense_metad_views_5be414_idx',
        ),
        migrations.RemoveIndex(
            model_name='aisensemetadata',
            name='sense_metad_is_offe_10ae69_idx',
        ),
        migrations.RemoveField(
            model_name='aisense',
            name='news',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='devoted',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='ipas',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='is_offensive',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='level',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='register',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='views',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='voted',
        ),
        migrations.AddField(
            model_name='aisense',
            name='devoted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='ipas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aisense',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aisense',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='pos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aisense',
            name='register',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='aisense',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisense',
            name='voted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aisensemetadata',
            name='advanced_contents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['score'], name='ai_sense_score_285081_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['likes'], name='ai_sense_likes_ba9693_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['views'], name='ai_sense_views_44026c_idx'),
        ),
        migrations.AddIndex(
            model_name='aisense',
            index=models.Index(fields=['is_offensive'], name='ai_sense_is_offe_5acb0a_idx'),
        ),
    ]
