# Generated by Django 4.2.20 on 2026-05-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_remove_aisense_ai_sense_previou_0e3f05_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aisensemetadata',
            old_name='advanced_contents',
            new_name='advanced',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='relateds',
        ),
        migrations.RemoveField(
            model_name='aisensemetadata',
            name='synonyms',
        ),
    ]
